deriv-com/p2p

src/components/DerivIframe/DerivIframe.tsx
changes:
- added missing `allow-same-origin` to iframe's `sandbox` attribute to fix the console error
=> fix: fixed console error for iframe

src/pages/advertiser/screens/AdvertiserAdvertsTable/AdvertiserAdvertsTable.tsx, src/pages/buy-sell/screens/BuySellHeader/BuySellHeader.tsx, src/pages/my-profile/screens/MyProfile/MyProfile.tsx, src/pages/orders/screens/Orders/OrdersTableHeader/OrdersTableHeader.tsx, src/utils/tabs.ts
https://github.com/deriv-com/p2p/assets/122768621/03d24dcf-0f86-4852-bd9c-e75c96616f18
Since the tab title is localized, and the tab components takes the tab title as the active tab, when switching the language, the tab doesn't work properly. hence need to pass the localized active tab to the tab component instead of the direct tab string.
this is a temporary fix, since changing the tab component to accept the index might affect the other apps.
=> nada/fix: handle tab switching when changing language

.github/workflows/build-and-deploy-test.yml
To distinguish test links from other deployments.
=> ako/ use testlinks CF token

src/components/AppHeader/MobileMenu/MenuContent.tsx, src/components/AppHeader/MobileMenu/MobileMenu.tsx, src/components/AppHeader/MobileMenu/__tests__/BackButton.spec.tsx, src/components/AppHeader/MobileMenu/__tests__/MenuContent.spec.tsx, src/components/AppHeader/MobileMenu/index.ts, src/hooks/__tests__/useNavigatorOnline.spec.tsx, src/hooks/__tests__/useNetworkStatus.spec.tsx, src/hooks/__tests__/useSyncedTime.spec.tsx
This PR includes:
- BackButton component tests
- MenuContent component tests
=> Niloofar/ Added test cases for BackButton and MenuContent components

src/hooks/__tests__/useFullScreen.spec.tsx, src/hooks/custom-hooks/useFullScreen.ts
This PR includes: 
- useFullScreen custom hook tests
=> Niloofar/ useFullScreen test cases

src/constants/url.ts
Developers are unable to manually set the endpoint as it gets overridden by the default setting in the code.
Implemented a check for localStorage data to ensure that the default `server_url` and `app_id` for staging are only set if the user hasn't previously configured them manually.
=> fix: fixed endpoint can't be set manually

src/components/Modals/FilterModal/__tests__/FilterModal.spec.tsx, src/pages/advertiser/screens/AdvertiserAdvertsTable/AdvertiserAdvertsTable.tsx, src/pages/advertiser/screens/AdvertiserAdvertsTable/__tests__/AdvertiserAdvertsTable.spec.tsx, src/pages/buy-sell/screens/BuySellHeader/BuySellHeader.tsx, src/pages/buy-sell/screens/BuySellHeader/__tests__/BuySellHeader.spec.tsx, src/pages/buy-sell/screens/BuySellTable/BuySellTable.tsx, src/pages/orders/screens/OrderDetails/OrderDetails.tsx, src/pages/orders/screens/OrderDetails/__tests__/OrderDetails.spec.tsx, src/pages/orders/screens/Orders/Orders.tsx, src/pages/orders/screens/Orders/OrdersTableHeader/OrdersTableHeader.tsx, src/pages/orders/screens/Orders/OrdersTableHeader/__tests__/OrdersTableHeader.spec.tsx, src/stores/index.ts, src/stores/useTabsStore.ts
- Added new store to handle the keeping the tab state throughout the user session
- Added for Buy/Sell, Orders and Advertisers page.
- Updated test cases where the component uses the stores
https://github.com/deriv-com/p2p/assets/103412909/07aaef3a-59be-4008-88ec-618c89db9826
=> Ameerul / FEQ-2459 Handling selected buy/sell and orders tabs

global.d.ts, src/hooks/custom-hooks/__tests__/useHandleRouteChange.spec.ts, src/hooks/custom-hooks/index.ts, src/hooks/custom-hooks/useHandleRouteChange.ts, src/routes/AppContent/index.tsx, src/routes/Router.tsx
- added the logic to send `page_load` and `allow_tracking` events to gtm so that core-web-vitals and google-analytics get triggered on p2p
=> feat: added page_load and allow_tracking events for gtm

index.html
Integrated script to initalise UTM data for marketing analytics
Tested with `http://localhost:5174/buy-sell?utm_source=adroll&utm_medium=ppc-display&utm_campaign=CCC&utm_campaign_id=DDD&utm_adgroup_id=EEE&signup_device=desktop`:
Tested with `http://localhost:5174/buy-sell?t=test&utm_source=AAA&utm_medium=BBB&utm_campaign=CCC`:
=> Added script for UTM initialisation

src/components/BlockedScenarios/BlockedScenarios.tsx
https://github.com/user-attachments/assets/2d1c9f79-2bd2-4f30-bf4a-6df5f105c4e7
=> fix: logo sizes

src/components/AdvertsTableRow/AdvertsTableRow.scss, src/components/BuySellForm/BuySellForm.tsx, src/pages/buy-sell/screens/BuySellTable/BuySellTable.scss, src/pages/orders/components/OrderDetailsCard/OrderDetailsCardFooter/OrderDetailsCardFooter.tsx, src/utils/format-value.ts
Set a default value for rate if it is not defined. Removed the extra Complain button and fixed alignment of list on Buy/Sell page.
=> farrah/FEQ-2543/fix: rate and button issues

src/components/Table/Table.tsx, src/hooks/api/advert/p2p-advert/useAdvertList.ts, src/hooks/custom-hooks/useFetchMore.ts, src/pages/advertiser/screens/AdvertiserAdvertsTable/AdvertiserAdvertsTable.tsx, src/pages/advertiser/screens/AdvertiserAdvertsTable/AdvertsTableRenderer/AdvertsTableRenderer.tsx, src/pages/buy-sell/screens/BuySellTable/BuySellTable.tsx, src/pages/buy-sell/screens/BuySellTable/BuySellTableRenderer/BuySellTableRenderer.tsx, src/pages/my-ads/screens/MyAds/MyAdsTable/MyAdsTable.tsx, src/pages/my-profile/screens/MyProfile/MyProfile.scss, src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterpartiesTable/MyProfileCounterpartiesTable.scss, src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterpartiesTable/MyProfileCounterpartiesTable.tsx, src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterpartiesTable/__tests__/MyProfileCounterpartiesTable.spec.tsx, src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterpartiesTableRow/MyProfileCounterpartiesTableRow.scss, src/pages/orders/screens/Orders/OrdersTable/OrdersTable.scss, src/pages/orders/screens/Orders/OrdersTable/OrdersTable.tsx
- Updated useFetchMore function and wrapped loadMore with debounce so it doesn't spam the loadMore function, as there are brief moments it will call it multiple times once it reaches the bottom.
- Migrated all Table components from deriv-com/ui to V2 version of it as theres a lot of ui issues if we try to upgrade the package
- Removed margin top for Loader in buy/sell page
- Fixed height scrolling issues in Orders and MyCounterparties tables
https://github.com/user-attachments/assets/afc6aad2-ef70-4b33-916c-8a5ada435c8c
https://github.com/user-attachments/assets/c3f293b3-78e7-4f4d-8803-17dff1038868
https://github.com/user-attachments/assets/b53ec38c-7caf-4cd3-a80c-b97022113cab
=> Ameerul / FEQ-2572 Multiple APIs are being called when scrolling to the end of the buy/sell and orders list

src/components/AdvertsTableRow/AdvertsTableRow.tsx, src/components/Modals/NicknameModal/NicknameModal.tsx, src/components/Modals/NicknameModal/__tests__/NicknameModal.spec.tsx, src/hooks/api/settings/p2p-settings/useSettings.ts, src/pages/advertiser/screens/AdvertiserAdvertsTable/AdvertiserAdvertsTable.scss, src/pages/buy-sell/screens/BuySellTable/__tests__/BuySellTable.spec.tsx, src/providers/AdvertiserInfoStateProvider/AdvertiserInfoStateProvider.tsx, src/routes/AppContent/index.tsx, src/routes/routes-config.ts
- Added hasCreatedAdvertiser value to Provider to know when the user has become an advertiser inside of AdvertsTableRow
- Added logic to show the BuySellForm after user has become an advertiser in Buy/Sell page and Advertiser page
- Exposed setP2PSettings here as well as this will fix the issue when non p2p but authenticated user logs in, and they click on Buy/Sell USD button, it wouldve shown the BuySellForm.
- Updated height for BuySellForm in advertiser page as it was a bit short
- Updated test cases for BuySellTable
https://github.com/user-attachments/assets/ba71d006-58c0-4d8c-99fe-693b0ec8346c
https://github.com/user-attachments/assets/254c37c0-5dbf-4b4b-b800-619d219adac4
https://github.com/user-attachments/assets/3cd40e73-8f45-4a0d-ab8c-95f7fd54f72f …
=> Ameerul / FEQ-2533 Once Adding nickname on clicking `Buy/Sell` USD or `Create Ad` button does not redirected to respective forms

src/components/BuySellForm/BuySellAmount/BuySellAmount.tsx, src/hooks/custom-hooks/useExtendedOrderDetails.ts
- passed decimal places prop as 2, for some reason, it doesn't do it by default when we format the money values to 2 by default, even though it mentions it would.
- Fixes issues in Buy/Sell modal, Order confirm modal, Order Info Header and Card info
=> Ameerul / FEQ-2587 Incorrect rate for floating rate order

src/components/PopoverDropdown/PopoverDropdown.tsx, src/components/PopoverDropdown/__tests__/PopoverDropdown.spec.tsx, src/hooks/custom-hooks/useIsAdvertiserBarred.ts, src/pages/my-ads/screens/MyAds/MyAdsTableRow/MyAdsTableRow.tsx
This pr fixes the issue where multiple api calls were placed for p2p_advertiser_adverts on page refresh
Before: 
https://github.com/user-attachments/assets/9ad7ef42-4b36-49f8-862d-a793ab87a3ae
After :
https://github.com/user-attachments/assets/7add7c19-38d7-4f47-826f-e95389859826
=> Nada/fix: advertiser table multiple api calls issue

.github/workflows/smoketests.yml
As suggested by Bala as it's not necessary now that we're only triggering from the deploy script.
=> Remove verify user step

src/components/AdvertsTableRow/AdvertsTableRow.tsx, src/components/BuySellForm/BuySellForm.tsx, src/components/BuySellForm/__tests__/BuySellForm.spec.tsx, src/components/Modals/ErrorModal/ErrorModal.scss, src/components/Modals/LoadingModal/LoadingModal.scss, src/components/Modals/LoadingModal/LoadingModal.tsx, src/components/Modals/ShareAdsModal/ShareAdsModal.tsx, src/components/Modals/ShareAdsModal/__tests__/ShareAdsModal.spec.tsx, src/pages/advertiser/screens/Advertiser/Advertiser.scss, src/pages/advertiser/screens/Advertiser/Advertiser.tsx, src/pages/advertiser/screens/AdvertiserAdvertsTable/AdvertiserAdvertsTable.scss, src/pages/advertiser/screens/AdvertiserAdvertsTable/AdvertiserAdvertsTable.tsx, src/pages/advertiser/screens/AdvertiserAdvertsTable/__tests__/AdvertiserAdvertsTable.spec.tsx, src/routes/Router.tsx
- Clear the search params after user closes the buy sell modal after opening a shared advert
- Remove currency from the p2p_advert_info call as BE included a change where we don't need to pass it anymore, just the id.
- Removed showing LoadingModal in Advertiser page, let it be handled internally in the BuySellForm, this will fix issues related to Buy showing by default before showing a Sell advert
- Hid the dropdown in responsive when the user is blocked
https://github.com/user-attachments/assets/bfc48fa5-658b-400c-9e01-5066be94a67d
=> Ameerul / FEQ-2661 Incorrect pop up displayed when advertiser tries to block another use

src/components/BuySellForm/BuySellForm.tsx
- Added advertiserPaymentMethods to the dependency array as it can go undefined after going idle, so this should refetch the data if this happens
=> Ameerul / WEBREL-3193 Payment Method disappears when create order page is idle

src/constants/url.ts
- Check if origin is equal to the p2p production origin as this was missing in the if check.
- Changed blue.derivws.com to green.derivws.com
=> Ameerul / FEQ-2669 The endpoint page is blank when loading p2p.deriv.com

src/App.tsx
- Wrapped Suspense Loader component in a div to position it in the centre. 
https://github.com/user-attachments/assets/80878213-4370-4716-8749-7cbeea7aecad
=> Ameerul / FEQ-2676 The loader icon is shifted towards the left corner of the screen when loading p2p.deriv.com

src/hooks/api/order/p2p-order/useOrderInfo.ts, src/hooks/custom-hooks/__tests__/useExtendedOrderDetails.spec.ts, src/hooks/custom-hooks/useExtendedOrderDetails.ts, src/pages/orders/components/OrderDetailsCard/OrderDetailsCardReview/OrderDetailsCardReview.tsx, src/pages/orders/screens/Orders/OrdersTableRow/OrdersTableRow.tsx
- Added new get values in useExtendedOrderDetails to return the correct value for if the user was rated previously and is recommended based on if it is their advert.
- added test cases
https://github.com/user-attachments/assets/c9f0f293-b64f-4dab-988a-b12170f51606
=> Ameerul / FEQ-2666 "No" is selected by default in rating and recommendation modal

jest.config.cjs, package-lock.json, package.json, src/hooks/custom-hooks/useOAuth.ts
Motivation 
- Currently the OAuth2 implementation is in the consumer app. 
Actions 
- Install and use [auth-client library](https://github.com/deriv-com/auth-client)
- Update the logout function to one
- Remove the isOAuth2Enabled check
- Remove the iframe and onMessage logic
=> chore: use oauth library

src/components/AdvertiserName/AdvertiserNameBadges.tsx, src/components/Badge/Badge.tsx, src/pages/advertiser/screens/Advertiser/Advertiser.scss
- Removed localize that was wrapping the variant strings in AdvertiserNameBadges
- Removed top 1rem for Advertiser page cause in some languages, it was appearing behind it like thai
https://github.com/user-attachments/assets/cfff92f9-c387-41d6-8caa-f818237171b5
=> Ameerul / FEQ-2682 On Switching the language from english , the badges are not visible on My profile page

src/hooks/custom-hooks/useOAuth.ts
Calling logout function onRender whenever its not authorized or authorizing, this is causing the SSO to not work cause its logging out the session before it hits the OAuth page and therefore the session is killed.
Changed the logic abit so we dont call logout but we go to the OAuth page and it will redirect us back correctly
=> chore: remove logout check

global.d.ts, package-lock.json, package.json, src/components/AppFooter/Livechat.tsx, src/components/AppFooter/__tests__/AppFooter.spec.tsx, src/components/AppHeader/MobileMenu/MobileMenuConfig.tsx, src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/Modals/AdErrorTooltipModal/AdErrorTooltipModal.tsx, src/components/Modals/AdVisibilityErrorModal/AdVisibilityErrorModal.tsx, src/components/Modals/AdVisibilityErrorModal/__tests__/AdVisibilityErrorModal.spec.tsx, src/components/Modals/OrderDetailsComplainModal/OrderDetailsComplainModal.tsx, src/components/OnboardingTooltip/OnboardingTooltip.tsx, src/hooks/custom-hooks/__tests__/useDerivAnalytics.spec.tsx, src/hooks/custom-hooks/useDerivAnalytics.ts, src/hooks/custom-hooks/useFreshchat.ts, src/hooks/custom-hooks/useGrowthbookGetFeatureValue.tsx, src/hooks/custom-hooks/useOAuth.ts, src/hooks/custom-hooks/useOAuth2Enabled.ts, src/pages/guide/screens/Awareness/Awareness.tsx, src/pages/guide/screens/FAQs/FAQs.tsx, src/pages/guide/screens/GettingStarted/GettingStarted.tsx, src/utils/__tests__/chat.spec.ts, src/utils/__tests__/get-country.spec.ts, src/utils/__tests__/get-featureflag.spec.ts, src/utils/chat.ts, src/utils/get-country.ts, src/utils/get-featureflag.ts
- Initial implementation of Freshchat
- Updated growthbook config
- Client's `country` is standardized via `cloudflare` for proper trigger of growthbook flag
`Note:` I need help for initial review, this is awaiting for the new hooks coming from deriv-app to properly handle the toggle of the current active chat widget.
=> CSIT-1563/Prince/ initial implementation of freshchat

src/components/BuySellForm/BuySellForm.tsx, src/components/BuySellForm/BuySellPaymentSection/BuySellPaymentSection.tsx, src/components/BuySellForm/BuySellPaymentSection/__tests__/BuySellPaymentSection.spec.tsx
- Filtered out available payment methods and return only the non available ones to handle showing the pm add cards
- Mapped out advertiser payment methods to ensure all payment methods are shown in Sell Order screen
- Added small logic to disable payment method card selection if user has already selected more than 3 payment methods
https://github.com/user-attachments/assets/b19fc527-2904-43ba-91ac-2fab456d6e3d
https://github.com/user-attachments/assets/a4159351-6b99-4468-9f61-892305fc7f3d
=> Ameerul / P2PS-4384 Some Payment method is not showing on Sell order modal

src/components/AppHeader/Notifications/Notifications.tsx, src/components/Modals/DailyLimitModal/DailyLimitModal.tsx, src/components/Modals/DailyLimitModal/__tests__/DailyLimitModal.spec.tsx, src/hooks/api/notification/__tests__/useNotificationList.spec.ts, src/hooks/api/notification/useNotificationList.ts, src/hooks/api/notification/useNotificationUpdate.ts
Since buildship code will be migrated completely, and since it shouldn't be used in the meantime, this PR is to remove it from FE codebase for now. 
This reverts commit 60d72b6c08479dc801a47450fbe7843c7e803f35.
=> Revert "Reapply "farrah/integrate buildship" (#399) (#403)"

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/hooks/custom-hooks/__tests__/useIsP2PBlocked.spec.ts, src/hooks/custom-hooks/useIsP2PBlocked.ts
- Added check for p2p_blocked_for_pa so Payment Agents will be blocked from entering p2p if this status is there under account status.
=> Ameerul / P2PS-4525 P2P is not block for Payment Agent

vercel.json
Added `vercel.json` to handle client-side routing in our Single Page Application (SPA) when deployed to Vercel. This configuration ensures that all routes are properly handled and prevents 404 errors when accessing paths directly or refreshing pages.
- Added `vercel.json` with route configuration to redirect all requests to index.html
- Enables proper functioning of client-side routing
- Fixes 404 errors on direct access to routes or page refreshes
=> added vercel.json to fix vercel dr publish

vercel.dr.json, vercel.json
Previous configuration with `routes` in `vercel.json` wasn't working with production deployment because the shared action (`vercel_DR_publish`) was overwriting it with `vercel.dr.json`. 
- Modified `vercel.dr.json` to include both build settings and SPA routing configuration
- Used `rewrites` instead of `routes` for better compatibility
- Removed `cleanUrls` as it was causing 404 errors on subpages when combined with `rewrites`
=> updated vercel.dr.json

src/components/AdvertiserName/AdvertiserNameBadges.tsx, src/components/AdvertiserName/__tests__/AdvertiserName.spec.tsx, src/components/AdvertiserName/__tests__/AdvertiserNameBadges.spec.tsx, src/components/AdvertsTableRow/AdvertsTableRow.tsx, src/components/Checklist/Checklist.scss, src/components/Checklist/Checklist.tsx, src/components/Modals/BlockUnblockUserModal/BlockUnblockUserModal.tsx, src/components/Verification/Verification.tsx, src/components/Verification/__tests__/Verification.spec.tsx, src/constants/api-error-codes.ts, src/hooks/api/settings/p2p-settings/useSettings.ts, src/hooks/custom-hooks/__tests__/useGetPhoneNumberVerification.spec.ts, src/hooks/custom-hooks/__tests__/useIsAdvertiserNotVerified.spec.ts, src/hooks/custom-hooks/__tests__/usePoiPoaStatus.spec.tsx, src/hooks/custom-hooks/index.ts, src/hooks/custom-hooks/useGetPhoneNumberVerification.ts, src/hooks/custom-hooks/useIsAdvertiserNotVerified.ts, src/hooks/custom-hooks/usePoiPoaStatus.ts, src/pages/advertiser/screens/AdvertiserAdvertsTable/__tests__/AdvertiserAdvertsTable.spec.tsx, src/pages/buy-sell/screens/BuySell/BuySell.tsx, src/pages/buy-sell/screens/BuySell/__tests__/BuySell.spec.tsx, src/pages/buy-sell/screens/BuySellTable/__tests__/BuySellTable.spec.tsx, src/pages/my-ads/screens/MyAds/MyAds.tsx, src/pages/my-ads/screens/MyAds/__tests__/MyAds.spec.tsx, src/pages/my-profile/screens/MyProfile/MyProfile.tsx, src/pages/my-profile/screens/MyProfile/__tests__/MyProfile.spec.tsx
- Added new hook to get phone number verification, user's phone number, check if pnv is enabled, check if Verification should be shown
- Replaced p2p_poa_required from get_account_status to poa_required from p2p_settings since it will be replaced in the future
- Updated Logic to show the Verification page for new users if pnv was enabled.
- Updated content to Verification component to include check if user's phone number is verified
- Updated checklist UI
- Updated test cases
- Updated search param from poi_poa_verified to verified to be more concise
https://github.com/user-attachments/assets/66c72cbe-d9ea-410d-aeae-25245d2d368f
=> Ameerul / P2PS-464 [FE] - Mandatory Mobile Number Verification for Deriv P2P (New User)

package-lock.json, package.json
Update quill-icons version to get the missing eUSDT icon.
=> farrah/chore: update quill icons version

src/components/AwarenessBanner/AwarenessBanner.scss, src/components/AwarenessBanner/AwarenessBanner.tsx, src/components/AwarenessBanner/__tests__/AwarenessBanner.spec.tsx, src/components/AwarenessBanner/index.ts, src/components/BuySellForm/BuySellForm.scss, src/components/Modals/FilterModal/FilterModal.scss, src/components/index.ts, src/pages/buy-sell/components/CurrencyDropdown/CurrencyDropdown.scss, src/pages/buy-sell/screens/BuySell/BuySell.tsx, src/pages/buy-sell/screens/BuySell/__tests__/BuySell.spec.tsx, src/pages/my-ads/components/AdFormTextArea/AdFormTextArea.tsx, src/pages/my-ads/components/AdTypeSection/AdTypeSection.scss, src/pages/my-ads/components/AdTypeSection/AdTypeSection.tsx, src/pages/my-ads/screens/MyAds/MyAds.scss, src/pages/my-ads/screens/MyAds/MyAds.tsx, src/pages/my-ads/screens/MyAdsEmpty/MyAdsEmpty.tsx, src/pages/my-profile/screens/MyProfile/MyProfile.tsx, src/pages/my-profile/screens/MyProfile/MyProfileMobile.tsx, src/pages/my-profile/screens/MyProfile/__tests__/MyProfileMobile.spec.tsx, src/pages/orders/components/OrderDetailsCard/OrderDetailsCardInfo/ActiveOrderInfo/ActiveOrderInfo.tsx, src/pages/orders/components/OrderDetailsCard/OrderDetailsCardInfo/ActiveOrderInfo/__tests__/ActiveOrderInfo.spec.tsx, src/pages/orders/screens/Orders/Orders.scss, src/pages/orders/screens/Orders/Orders.tsx, src/pages/orders/screens/Orders/OrdersTable/OrdersTable.scss, src/pages/orders/screens/Orders/__tests__/Orders.spec.tsx
Added an awareness banner, removed the contact details, and added validations for instructions.
=> farrah/feat: awareness banner

global.d.ts, src/components/AppFooter/Livechat.tsx, src/components/AppHeader/HeaderConfig.tsx, src/components/AppHeader/MenuItems/MenuItems.tsx, src/components/AppHeader/MobileMenu/MobileMenuConfig.tsx, src/components/AppHeader/MobileMenu/__tests__/MobileMenu.spec.tsx, src/components/AppHeader/PlatformSwitcher/PlatformSwitcher.tsx, src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/hooks/api/account/useActiveAccount.ts, src/hooks/custom-hooks/index.ts, src/hooks/custom-hooks/useGrowthbookGetFeatureValue.tsx, src/hooks/custom-hooks/useShouldRedirectToLowCodeHub.ts
- Added logic to redirect to low code tradershub or cfds if the current logged in user is using a wallet account, or if the `hub_enabled_country_list_p2p` feature flag contains the country of the user
=> Ameerul / P2PS-5203 Linking of low-code/ high-code for redirections & Logins

src/hooks/custom-hooks/useOAuth.ts
Currently OIDC logged_state cookies checks only triggers in Safari, for backward compatability we still check the cookies and log them out if logged_state is `false`
=> Adrienne / Support backward compatability for oidc cookies

src/routes/CallbackPage.tsx
- Check acct using .includes as the acct can be CR00000 for example, not just CR. So need to check if it CR is included in the string. Cross checked with deriv-api-hooks as this is the same logic we have there
=> Ameerul / WEBREL-3818 Redirection P2P is not working as expected when user created a USDC account first and then adds fiat account 

src/hooks/custom-hooks/useOAuth.ts, src/routes/AppContent/index.tsx, src/routes/CallbackPage.tsx
- Added try catch around logout in `WSLogoutAndRedirect` and `handleLogout` as we did not handle the exception, thus it froze and never did anything else after being called.
- Added a check top level where we cross check the currencies between authorize account list data, and the OIDC tokens. If the currency is not included in the OIDC tokens or if the length of both currency lists do not match.
=> Ameerul / ENGT-1800 OIDC Logout freeze issue and Seeing page error in P2P when login with client who previously login to P2P using non USD account.

src/hooks/custom-hooks/useOAuth.ts, src/routes/AppContent/index.tsx
- Added try catch around requestOIDCAuthentication
- Changed if to dismiss loader if isOAuth2Enabled as when you're in endpoint page, login button never shows if user never logged in previously
=> Ameerul / TRAH-5948 Fix logout issue firefox

src/pages/buy-sell/components/CurrencyDropdown/CurrencySelector/CurrencySelector.tsx
- Added gap-1 for the div that has country name and currency in CurrencyDropdown
=> Ameerul / P2PS-5233 Improve Spacing Between Country Name and Currency Denominator

src/hooks/api/advert/p2p-advert/useAdvertList.ts
- Sorted the p2p_adverts_list response by is_eligible. is_eligible = 0 will be pushed to the bottom.
=> Ameerul / P2PS-5221 Move/Hide Ineligible Ads to the Bottom of the Buy/Sell Page

src/components/AdvertsTableRow/AdvertsTableRow.tsx, src/hooks/api/advert/p2p-advert/useAdvertList.ts
- Filtered non eligible adverts and eligible adverts then combined to two together, since last time it filtered by comparing the advert with the next advert and our own advert doesn't have is_eligible flag in the object
- Also fixed long names in advert list since it would push the whole column
=> Ameerul / WEBREL-3927 Sort Functionality - User's Own Ad is coming on Top of the list

src/components/AppHeader/AppHeader.tsx
- Added an extra check with isCheckingOidcToken since this is the only thing that could affect the loader in the header since the user is in endpoint page and acctiveAccount is false
=> Ameerul / WEBREL-3932 Unable To Load The Endpoint Page Header

src/components/Modals/RemainingBuySellLimitModal/RemainingBuySellLimitModal.scss, src/components/Modals/RemainingBuySellLimitModal/RemainingBuySellLimitModal.tsx, src/components/Modals/RemainingBuySellLimitModal/__tests__/RemainingBuySellLimitModal.spec.tsx, src/components/Modals/RemainingBuySellLimitModal/index.ts, src/components/Modals/index.ts, src/components/ProfileContent/ProfileBalance/ProfileBalance.scss, src/components/ProfileContent/ProfileBalance/ProfileBalance.tsx, src/components/ProfileContent/ProfileBalance/__tests__/ProfileBalance.spec.tsx, src/components/ProfileContent/ProfileContent.scss
Added a modal for showing the remaining buy/sell limit info.
=> fix: update buy/sell limit info

src/App.tsx, src/components/AppHeader/AppHeader.tsx, src/hooks/custom-hooks/useTMB.ts
- Render `useEffect` only once, as currently it is rendering multiple times, slowing down the application initialization
- Remove Hydra redirects if `TMB` flag is enabled all together. 
- As per BE, no need to do OAuth logout in case of TMB session
- Token sequence can be random from `/active` endpoint
- Updated logic to get the save the appropriate auth token as per logic from `/callback` page
=> Remove OIDC redirects if TMB flag is active

package-lock.json, package.json, src/App.tsx, src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/constants/account.ts, src/constants/index.ts, src/hooks/custom-hooks/__tests__/useIsP2PBlocked.spec.ts, src/hooks/custom-hooks/useIsP2PBlocked.ts, src/main.tsx, src/routes/CallbackPage.tsx
Handle the scenarios for authorizing accounts when redirecting from Trader's Hub OS to P2P. Instead of only authorizing USD account by default, we need to authorize non-USD real accounts too.
=> farrah/fix: authorizing of accounts

src/routes/AppContent/index.tsx
- Added popstate window listener to listen when the user clicks the back button for browser. If they do, and it tries to navigate to the base route when trying to return to deriv app or other apps, it will keep looping and navigating backwards until they are navigated to the original origin.
=> Ameerul / ENGT-2414 On Responsive mode seeing Infinite loading on tapping Back button from P2P page

src/components/Modals/BusinessHoursModal/BusinessHoursModal.tsx, src/components/Modals/BusinessHoursModal/__tests__/BusinessHoursModal.spec.tsx
- replaced mutate with mutateAsync, this way we properly await for the mutation to be done, then call setShowEdit with false to hide the edit page.
=> Ameerul / P2PS-5330 [Edit Business Hours] - Unable to close edit business hour dialog

.github/workflows/sync-translations.yml
Potential fix for [https://github.com/deriv-com/p2p/security/code-scanning/10](https://github.com/deriv-com/p2p/security/code-scanning/10)
To fix the issue, we need to add an explicit `permissions` block to the workflow. This block will specify the minimal privileges required for the workflow's tasks. Based on the workflow's purpose:
- The `contents: read` permission is necessary to allow the workflow to read repository files during the checkout step.
- Other permissions, such as `contents: write`, are not explicitly required for the tasks shown in the workflow and should be avoided.
The `permissions` block can be added at the root level of the workflow file to apply to all jobs or within the specific job (`sync_translations`) for fine-grained control.
---
_Suggested fixes powered by …
=> Potential fix for code scanning alert no. 10: Workflow does not contain permissions

.github/workflows/coveralls.yml
Potential fix for [https://github.com/deriv-com/p2p/security/code-scanning/7](https://github.com/deriv-com/p2p/security/code-scanning/7)
To fix the issue, we will add a `permissions` block to the workflow. Since the workflow primarily involves checking out the repository, setting up Node.js, installing dependencies, running tests, and reporting coverage, it only requires `contents: read` permissions. This ensures that the workflow has the minimal access necessary to perform its tasks.
The `permissions` block will be added at the root of the workflow file, applying to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 7: Workflow does not contain permissions

.github/workflows/build-and-deploy-staging.yml
Potential fix for [https://github.com/deriv-com/p2p/security/code-scanning/5](https://github.com/deriv-com/p2p/security/code-scanning/5)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will define the minimal permissions required for the workflow to function correctly. Based on the actions used in the workflow, the following permissions are likely required:
- `contents: read` for accessing the repository's contents.
- `pages: write` for publishing to Cloudflare Pages.
- `id-token: write` if any actions require OIDC tokens (not explicitly seen here but may be needed for some secrets).
The `permissions` block will be added after the `name` field at the top of the file.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before …
=> Potential fix for code scanning alert no. 5: Workflow does not contain permissions
