deriv-com/p2p

.github/workflows/coveralls.yml, README.md, src/components/AppHeader/__tests__/AppHeader.spec.tsx
Seems like there is a problem with running Coveralls on the PRs. this PR is for fixing that.
=> Niloofar/ Fix coveralls issue

localstorage-sync.html, src/App.tsx, src/components/DerivIframe/DerivIframe.tsx, src/components/DerivIframe/index.ts, src/components/index.ts
- added an iframe with an eventListener to listen for new messages to update the localStorage with the deriv-app
=> feat: added iframe with eventListener for coming messages

src/components/FullPageMobileWrapper/FullPageMobileWrapper.scss, src/pages/advertiser/screens/Advertiser/Advertiser.scss, src/pages/buy-sell/screens/BuySellTable/BuySellTable.scss, src/pages/my-ads/screens/MyAds/MyAds.tsx, src/pages/orders/components/ChatMessages/ChatMessages.scss, src/pages/orders/screens/OrderDetails/OrderDetails.scss, src/pages/orders/screens/OrdersChatSection/OrdersChatSection.scss, src/pages/orders/screens/OrdersChatSection/OrdersChatSection.tsx, src/routes/AppContent/index.scss, src/routes/AppContent/index.tsx
=> farrah/add Deriv P2P title

src/components/AdvertsTableRow/AdvertsTableRow.tsx, src/components/BuySellForm/BuySellAmount/BuySellAmount.tsx, src/components/BuySellForm/BuySellForm.scss, src/components/BuySellForm/BuySellForm.tsx, src/components/BuySellForm/BuySellFormDisplayWrapper.tsx, src/components/BuySellForm/BuySellPaymentSection/BuySellPaymentSection.tsx, src/components/BuySellForm/BuySellPaymentSection/__tests__/BuySellPaymentSection.spec.tsx, src/components/BuySellForm/__tests__/BuySellForm.spec.tsx, src/pages/advertiser/screens/Advertiser/Advertiser.scss, src/pages/advertiser/screens/Advertiser/Advertiser.tsx
Opening PM Form in sell form, should close the sell form and open it again when PM modal is closed
https://github.com/deriv-com/p2p/assets/122768621/5f8b3031-4284-48ca-a983-1a9eb99deff0
Font size issues, PM field in buyselltable, issues in advertiser page header
Confirm button not enabled for first time in buysellform even when values are filled
=> nada/fix: ui issues in buy sell flow

localstorage-sync.html
changes:
- added `uat-app.deriv.com` to allowed origins list in the iframe
=> chore: updated allowed origin list in deriv-app iframe

package-lock.json, package.json, src/components/BuySellForm/BuySellForm.tsx, src/components/Modals/BlockUnblockUserModal/BlockUnblockUserModal.tsx, src/components/Modals/InvalidVerificationLinkModal/InvalidVerificationLinkModal.tsx, src/components/Modals/NicknameModal/NicknameModal.tsx, src/components/PaymentMethodForm/PaymentMethodFormModalRenderer/PaymentMethodFormModalRenderer.tsx, src/hooks/custom-hooks/useIsAdvertiser.ts, src/pages/my-ads/screens/CreateEditAd/CreateEditAd.tsx, src/pages/my-ads/screens/MyAds/MyAdsTableRow/MyAdsTableRowView.tsx, src/pages/my-profile/screens/PaymentMethods/PaymentMethodsList/PaymentMethodsListContent/PaymentMethodsListContent.tsx, src/pages/orders/components/OrderDetailsCard/OrderDetailsCardFooter/OrderDetailsCardFooter.tsx, src/pages/orders/screens/OrderDetails/OrderDetails.tsx, src/pages/orders/screens/Orders/OrdersTableRow/OrdersTableRow.tsx, src/routes/AppContent/index.tsx
- This update fixes the type issues with error returned from all apis.
- Removed all ts-expect-errors / ts-no-checks
=> Ameerul / Updated api-hooks package to 1.1.2

src/components/AppHeader/MobileMenu/__tests__/ToggleButton.spec.tsx
This PR includes:
- ToggleButton test cases
=> Niloofar/ Added tests for ToggleButton component

src/components/AppHeader/MobileMenu/__tests__/MenuHeader.spec.tsx
This PR includes:
- MenuHeader component test cases
=> Niloofar/ Added tests for MenuHeader component

src/components/AppHeader/MobileMenu/MobileMenu.tsx, src/components/AppHeader/MobileMenu/index.ts, src/hooks/__tests__/useNavigatorOnline.spec.tsx, src/hooks/__tests__/useNetworkStatus.spec.tsx, src/hooks/__tests__/useSyncedTime.spec.tsx
This PR contains: 
- useSyncedTime tests
- useNetworkStatus tests
- useNavigatorOnline tests
- update the exports in sideMenu for consistency
=> Niloofar/ Added test cases for Footer custom hooks

src/components/AppHeader/MobileMenu/__tests__/MobileMenu.spec.tsx
This PR includes:
- MobileMenu component tests
=> Niloofar/ Added tests for MobileMenu component

src/utils/__tests__/payment-methods.spec.ts, src/utils/payment-methods.ts
- Added test coverage for payment-methods.ts util file
=> Ameerul / FEQ-2327 Add test coverage for payment-methods.ts

__mocks__/LocalizeMock.js, src/components/Modals/OrderDetailsComplainModal/OrderDetailsComplainModalRadioGroup/OrderDetailsComplainModalRadioGroup.tsx, src/components/PaymentMethodCard/PaymentMethodCardHeader/PaymentMethodCardHeader.tsx, src/components/Verification/Verification.tsx, src/utils/__tests__/adverts.spec.ts, src/utils/adverts.ts
=> Nada/FEQ-2325/chore: added unit test for advert utility function

src/utils/__tests__/order-utils.spec.ts
=> Nada/FEQ-2328/chore: unit test for order-utils

src/components/Modals/OrderDetailsConfirmModal/OrderDetailsConfirmModal.tsx, src/components/Modals/OrderDetailsConfirmModal/__tests__/OrderDetailsConfirmModal.spec.tsx
https://github.com/deriv-com/p2p/assets/122768621/deffa9f9-9399-413f-8466-c682e7048fc1
=> Nada/FEQ-2383/disable confirm button if file is not uploaded/supported

src/utils/__tests__/time.spec.ts, src/utils/time.ts
- Added test cases for time.ts util
- Slightly refactored time.ts
=> Ameerul / FEQ-2380 Add test coverage for time.ts

src/components/Modals/FilterModal/FilterModal.scss, src/components/Modals/FilterModal/FilterModal.tsx, src/components/Modals/FilterModal/FilterModalContent/FilterModalContent.tsx, src/components/Modals/FilterModal/FilterModalPaymentMethods/FilterModalPaymentMethods.scss, src/components/Modals/FilterModal/__tests__/FilterModal.spec.tsx, src/components/Modals/LeaveFilterModal/LeaveFilterModal.scss, src/components/Modals/LeaveFilterModal/LeaveFilterModal.tsx, src/components/Modals/LeaveFilterModal/__tests__/LeaveFilterModal.spec.tsx, src/components/Modals/LeaveFilterModal/index.ts, src/components/Modals/index.ts
https://github.com/deriv-com/p2p/assets/122768621/008a15a5-da9a-41f7-b668-feca338aba10
https://github.com/deriv-com/p2p/assets/122768621/20487f0b-32ff-4518-b110-4745e15ed16c
=> Nada/FEQ-2381/feat: add cancel modal for filter

package-lock.json, package.json, src/components/AppFooter/AccountLimits.tsx, src/components/AppFooter/ChangeTheme.tsx, src/components/AppFooter/Deriv.tsx, src/components/AppFooter/FullScreen.tsx, src/components/AppFooter/HelpCentre.tsx, src/components/AppFooter/LanguageSettings.tsx, src/components/AppFooter/Livechat.tsx, src/components/AppFooter/NetworkStatus.tsx, src/components/AppFooter/ResponsibleTrading.tsx, src/components/AppFooter/ServerTime.tsx, src/components/AppFooter/WhatsApp.tsx, src/components/AppFooter/__tests__/AppFooter.spec.tsx, src/components/AppHeader/AppHeader.tsx, src/components/AppHeader/Notifications/index.tsx, src/components/PopoverDropdown/PopoverDropdown.tsx, src/components/TooltipMenuIcon/TooltipMenuIcon.scss, src/components/TooltipMenuIcon/TooltipMenuIcon.tsx, src/components/TooltipMenuIcon/__test__/TooltipMenuIcon.spec.tsx, src/components/TooltipMenuIcon/index.ts, src/pages/my-ads/components/OrderTimeSelection/OrderTimeSelection.tsx
This PR contains temporary fix of this raised issue:
https://github.com/deriv-com/p2p/assets/93518187/5f764bd3-14eb-4914-b5db-3f1f9be537a8
=> Niloofar/ Fix Tooltip Component Issues

src/hooks/api/order-dispute/p2p-order-dispute/__tests__/useOrderDispute.spec.ts, src/hooks/api/order-dispute/p2p-order-dispute/useOrderDispute.ts
=> Nada/FEQ-2425/chore: unit test for use order dispute

src/hooks/custom-hooks/__tests__/useAdvertiserStats.spec.ts
- Added test cases for useAdvertiserStats
=> Ameerul / FEQ-2392 Add test coverage for useAdvertiserStats

src/hooks/api/order-review/p2p-order-review/__tests__/useOrderReview.spec.ts, src/hooks/api/order-review/p2p-order-review/useOrderReview.ts
=> Nada/FEQ-2426/chore: unit test for order review

src/hooks/custom-hooks/__tests__/useCopyToClipboard.spec.ts, src/hooks/custom-hooks/useCopyToClipboard.ts
- Added test cases for useCopyToClipboard
- added await to properly await for promise returned from copy function
=> Ameerul / FEQ-2393 Add test coverage for useCopyToClipboard

src/hooks/custom-hooks/__tests__/useExtendedOrderDetails.spec.ts, src/hooks/custom-hooks/useExtendedOrderDetails.ts
- Added test cases for useExtendedOrderDetails
=> Ameerul / FEQ-2394 Add test coverage for useExtendedOrderDetails

src/hooks/api/order/p2p-order/__tests__/useOrderInfo.spec.ts
- Added test coverage for useOrderInfo
=> Ameerul / FEQ-2423 Add test coverage for useOrderInfo

src/hooks/api/account/__tests__/useActiveAccount.spec.ts, src/hooks/api/account/useActiveAccount.ts
=> Nada/FEQ-2400/chore: add unit tests for useactiveaccount

src/hooks/api/advert/p2p-advert/__tests__/useAdvertCreate.spec.ts, src/hooks/api/advert/p2p-advert/__tests__/useAdvertDelete.spec.ts, src/hooks/api/advert/p2p-advert/__tests__/useAdvertUpdate.spec.ts, src/hooks/api/advert/p2p-advert/useAdvertCreate.ts, src/hooks/api/advert/p2p-advert/useAdvertDelete.ts, src/hooks/api/advert/p2p-advert/useAdvertUpdate.ts
=> Nada/FEQ-2405/chore: unit tests for advert create, update, delete

src/hooks/api/settings/p2p-settings/__tests__/useSettings.spec.ts, src/hooks/api/settings/p2p-settings/useSettings.ts, src/hooks/custom-hooks/useFloatingRate.ts, src/pages/buy-sell/components/CurrencyDropdown/CurrencyDropdown.tsx, src/pages/buy-sell/components/CurrencyDropdown/__tests__/CurrencyDropdown.spec.tsx
- Added test cases for useP2PSettings
- Updated snake case values to camel case
=> Ameerul / FEQ-2432 Add test coverage for useP2PSettings

src/hooks/api/order/p2p-order/__tests__/useOrderList.spec.ts, src/hooks/api/order/p2p-order/useOrderList.ts
- added test coverage for useOrderList
=> Ameerul / FEQ-2424 Add test coverage for useOrderList

src/components/DatePicker/DatePicker.tsx, src/hooks/custom-hooks/__tests__/useSendbird.spec.ts
=> Nada/FEQ-2399/chore: unit test for usesendbird

src/hooks/api/payment-method/p2p-advertiser-payment-methods/__tests__/useAdvertiserPaymentMethods.spec.ts, src/hooks/api/payment-method/p2p-advertiser-payment-methods/__tests__/useCreateAdvertiserPaymentMethods.spec.ts, src/hooks/api/payment-method/p2p-advertiser-payment-methods/__tests__/useDeleteAdvertiserPaymentMethods.spec.ts, src/hooks/api/payment-method/p2p-advertiser-payment-methods/__tests__/useUpdateAdvertiserPaymentMethods.spec.ts, src/hooks/api/payment-method/p2p-advertiser-payment-methods/useAdvertiserPaymentMethods.ts, src/hooks/api/payment-method/p2p-payment-methods/__tests__/usePaymentMethods.spec.ts, src/hooks/api/payment-method/p2p-payment-methods/usePaymentMethods.ts
unit test for payment methods
advertiserpaymentmethods
createadvertiserpaymentmethods
updateadvertiserpaymentmethods
deleteadvertiserpaymentmethods
=> FEQ-2431 / chore: unit tests for payment methods

src/components/Modals/AvailableP2PBalanceModal/AvailableP2PBalanceModal.scss, src/components/Modals/AvailableP2PBalanceModal/AvailableP2PBalanceModal.tsx
- Used Modal component from deriv-com/ui
- Refactored the styles
=> Ameerul / FEQ-2448 Refactor AvailableP2PBalanceModal

src/components/Modals/DailyLimitModal/DailyLimitModal.scss, src/components/Modals/DailyLimitModal/DailyLimitModal.tsx, src/components/ProfileContent/ProfileContent.scss, src/components/ProfileContent/ProfileDailyLimit/ProfileDailyLimit.tsx, src/components/ProfileContent/ProfileDailyLimit/__tests__/ProfileDailyLimit.spec.tsx
https://github.com/deriv-com/p2p/assets/122768621/acb86ea3-89c6-489e-939a-9399e1c36c13
=> Nada/FEQ 2447/: daily limit modal refactor

.github/workflows/build-and-deploy-prod.yml
=> Nada/fix: translation env for prod build

src/components/Modals/PreferredCountriesModal/PreferredCountriesModal.scss, src/components/PaymentMethodForm/PaymentMethodForm.scss, src/components/PaymentMethodForm/PaymentMethodForm.tsx, src/components/PaymentMethodForm/PaymentMethodFormModalRenderer/PaymentMethodFormModalRenderer.tsx, src/components/PaymentMethodForm/__test__/PaymentMethodForm.spec.tsx, src/components/PaymentMethodsFormFooter/PaymentMethodsFormFooter.tsx, src/pages/my-ads/components/AdConditionsSection/AdConditionsSection.tsx, src/pages/my-ads/components/AdConditionsSection/AdCondtionsSection.scss, src/pages/my-ads/components/AdFormController/AdFormController.scss, src/pages/my-ads/components/SellAdPaymentSelection/SellAdPaymentSelection.scss, src/pages/my-profile/screens/MyProfile/MyProfile.scss, src/pages/my-profile/screens/MyProfileAdDetails/MyProfileAdDetails.scss, src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterparties.tsx, src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterpartiesTable/MyProfileCounterpartiesTable.scss, src/pages/my-profile/screens/MyProfileStats/MyProfileStatsMobile.tsx, src/pages/my-profile/screens/PaymentMethods/PaymentMethodsEmpty/PaymentMethodsEmpty.scss, src/pages/my-profile/screens/PaymentMethods/PaymentMethodsList/PaymentMethodsList.scss
- Fixed style issues for FullPageModal not being fully at the top of the page
- Fixed style issues on responsive for Create/Edit advert
- Fixed scrolling issues when adding payment method in my profile
- handled any errors when error comes from creating or updating a payment method
- updated test cases
https://github.com/deriv-com/p2p/assets/103412909/14d82f92-a38c-4089-8b03-b195423cc4f6
https://github.com/deriv-com/p2p/assets/103412909/bc41a5e5-bb36-4fc6-8cb2-8c9e765666be
https://github.com/deriv-com/p2p/assets/103412909/3a660ece-2f89-46c6-8880-7014eac6d148
https://github.com/deriv-com/p2p/assets/103412909/d1d2e76f-f0c2-4c5a-9905-3622ecbc7c12
https://github.com/deriv-com/p2p/assets/103412909/76a05766-aaa7-4e44-969a-9369336ab8f7
https://github.com/deriv-com/p2p/assets/103412909/676a084f-8b …
=> Ameerul / FEQ-2439 Add a validation for duplicate payment methods

src/components/Modals/FilterModal/FilterModal.tsx, src/components/Modals/FilterModal/__tests__/FilterModal.spec.tsx, src/pages/buy-sell/components/CurrencyDropdown/CurrencyDropdown.scss, src/pages/buy-sell/components/CurrencyDropdown/CurrencyDropdown.tsx, src/pages/buy-sell/components/SortDropdown/SortDropdown.tsx, src/pages/buy-sell/screens/BuySellHeader/BuySellHeader.scss, src/pages/buy-sell/screens/BuySellHeader/BuySellHeader.tsx
Add buy sell filter indicator
Fixed issue where it was shown 'all' for none of the pm are selected
https://github.com/deriv-com/p2p/assets/122768621/9617e395-ff00-4d3b-9022-dde6e5702f47
=> Nada/feat: add status indicator for buy sell pm filter

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/constants/api-error-codes.ts, src/hooks/custom-hooks/__tests__/useIsP2PBlocked.spec.ts, src/hooks/custom-hooks/index.ts, src/hooks/custom-hooks/useIsP2PBlocked.ts, src/routes/AppContent/index.tsx
- Added flows for Permission Denied, perm banned user, cashier is locked, system maintenance
- Added new custom hook useIsP2PBlocked
- Updated content in BlockedScenarios
https://github.com/deriv-com/p2p/assets/103412909/0a19542e-662d-4879-936a-64852e05f68b
https://github.com/deriv-com/p2p/assets/103412909/3c3adee0-046c-46ec-82d9-31ac99986372
https://github.com/deriv-com/p2p/assets/103412909/1dafa2a5-b13d-4fbe-b370-0690eba2c9f8
https://github.com/deriv-com/p2p/assets/103412909/1d17ca07-bca0-49d8-858a-829a075d2135
https://github.com/deriv-com/p2p/assets/103412909/259defa7-d2c2-4c25-a479-2967a0b207a7
=> Ameerul / FEQ-2453 Show a message if the user is banned from using P2P

.github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml
- added two new variables for trackjs
=> ci: add new env variables in the build step

.github/workflows/build-and-deploy-prod.yml, .github/workflows/build-and-deploy-staging.yml, package-lock.json, package.json, src/App.tsx, src/constants/firebase-init-data.ts, src/constants/index.ts, src/hooks/custom-hooks/__tests__/useDerivAnalytics.spec.tsx, src/hooks/custom-hooks/__tests__/useTrackjs.spec.tsx, src/hooks/custom-hooks/index.ts, src/hooks/custom-hooks/useDerivAnalytics.ts, src/hooks/custom-hooks/useTrackjs.ts
- added a new hook called `useDerivAnalytics`
- updated stating and production deployment workflows to include growthbook and rudderstack tokens
- improved trackjs initialisation call
- installed `js-cookie` library
=> Shayan/FEQ-2467/setup deriv-analytics

src/hooks/custom-hooks/useDerivAnalytics.ts
- replaced `useTranslation` with localStorage to fetch the current language
=> fix: updated the way we fetch currentLang

.github/workflows/build-and-deploy-prod.yml, .github/workflows/build-and-deploy-staging.yml, package-lock.json, package.json, src/hooks/custom-hooks/__tests__/useDerivAnalytics.spec.tsx, src/hooks/custom-hooks/useDerivAnalytics.ts
- added `VITE_REMOTE_CONFIG_URL` to the workflow
- updated `@deriv-com/analytics` version
- updated test file for `useDerivAnalytics` 
- disabled deriv-analytics for localhost
=> fix: fixed cookie issue

src/components/AppHeader/AccountSwitcher/AccountSwitcher.tsx, src/components/AppHeader/AccountSwitcher/index.ts, src/components/AppHeader/AccountsInfoLoader/AccountsInfoLoader.tsx, src/components/AppHeader/AccountsInfoLoader/index.ts, src/components/AppHeader/AppHeader.tsx, src/components/AppHeader/AppLogo/AppLogo.tsx, src/components/AppHeader/AppLogo/index.ts, src/components/AppHeader/MenuItems/MenuItems.tsx, src/components/AppHeader/MenuItems/index.ts, src/components/AppHeader/Notifications/Notifications.tsx, src/components/AppHeader/Notifications/index.ts, src/components/AppHeader/PlatformSwitcher/PlatformSwitcher.tsx, src/components/AppHeader/PlatformSwitcher/index.ts
=> Nada/fix: restructure the folders for consistency

index.html, package-lock.json, package.json, src/components/DerivIframe/DerivIframe.tsx
PR Change:
- Added Vite bundle analyzer script
- Added title for the iFrames to improve accessibility 
- Moved Vite-related packages to devDependencies
=> Matin/FEQ-2526/Add Vite bundle analyzer

src/components/AdvertsTableRow/AdvertsTableRow.scss, src/pages/buy-sell/screens/BuySellTable/BuySellTableRenderer/BuySellTableRenderer.tsx, src/pages/orders/components/OrderDetailsCard/OrderDetailsCardFooter/OrderDetailsCardFooter.tsx
Fixed the list of bugs raised.
=> farrah/FEQ-2498/fix: bugs list

package-lock.json, package.json, src/components/AppHeader/AppHeader.tsx, src/components/AppHeader/MobileMenu/MobileMenuConfig.tsx
- @deriv-com/api-hooks logout() functionality now calls the logout api call
- logout is now an async call
- redirect to OAuth once done
=> yashim/fix: logout

.github/workflows/build-and-deploy-prod.yml, .github/workflows/build-and-deploy-staging.yml, src/App.tsx, src/hooks/custom-hooks/useGrowthbookGetFeatureValue.tsx, src/hooks/custom-hooks/useIsGrowthbookLoaded.tsx
This is to use Growthbook featureflag to redirect back the clients to deriv-app if the flag is disabled.
=> Ako/ add gb feature flag

package-lock.json, package.json, src/hooks/custom-hooks/useDerivAnalytics.ts
- updated `@deriv-com/translations` to version `1.3.6`
- replace `localStorage.getItem()` with `LocalStorageUtils.getValue()`
=> Shayan/ Update translation package

src/components/AdvertsTableRow/AdvertsTableRow.tsx, src/utils/__tests__/ad-utils.spec.ts, src/utils/ad-utils.ts
Added onClick handler for arrow in buy/sell list and fixed the translation for eligibility messages.
=> farrah/fix: bug list

src/hooks/api/settings/p2p-settings/useSettings.ts, src/routes/AppContent/index.tsx
- Cleared the p2p_settings local storage value since it would set the local currency from the previous data, before it gets updated.
https://github.com/user-attachments/assets/5a928b08-0f72-41e1-a6ad-1a1c12d41ed5
=> Ameerul / FEQ-2548 Local currency is not shown as default on currency dropdown

src/components/AppHeader/MobileMenu/MenuContent.tsx, src/components/AppHeader/MobileMenu/MobileMenuConfig.tsx, src/components/AppHeader/PlatformSwitcher/PlatformSwitcher.scss, src/components/AppHeader/PlatformSwitcher/PlatformSwitcher.tsx
- Added padding to the dropdown in responsive
- Made the platform switcher scrollable in responsive
- Fixed the redirection link to traders hub for `'Looking for CFDs? Go to Trader’s Hub'` text
https://github.com/user-attachments/assets/e13f005d-76f0-4202-9758-423c3610e50d
=> Ameerul / FEQ-2584 Platform switcher dropdown UI bug

src/components/AdvertiserName/AdvertiserName.tsx, src/components/AdvertiserName/__tests__/AdvertiserName.spec.tsx
- Changed logic to show your nickname only in MyProfile
- Updated test cases for AdvertiserName
https://github.com/user-attachments/assets/b1df0fe2-1c99-4ddb-bf40-05fa248eb3a6
=> Ameerul / FEQ-2557 Advertiser seeing his own real-name when going to another advertiser's profile.

src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterparties.scss, src/pages/my-profile/screens/MyProfileCounterparties/MyProfileCounterpartiesTable/MyProfileCounterpartiesTable.scss
- Fixed the height style for counterparties table
https://github.com/user-attachments/assets/4cc27759-4768-4a59-902a-c90f8c5cb7fc
=> Ameerul / FEQ-2594 My Counterparties page is broken

package-lock.json, package.json, src/hooks/custom-hooks/__tests__/useDotButton.spec.ts, src/hooks/custom-hooks/index.ts, src/hooks/custom-hooks/useDotButton.ts, src/pages/guide/components/Carousel/Carousel.scss, src/pages/guide/components/Carousel/Carousel.tsx, src/pages/guide/components/Carousel/__tests__/Carousel.spec.tsx, src/pages/guide/components/GuideTooltip/GuideTooltip.scss, src/pages/guide/components/GuideTooltip/GuideTooltip.tsx, src/pages/guide/screens/Awareness/__tests__/Awareness.spec.tsx, src/pages/guide/screens/Blog/Blog.tsx, src/pages/guide/screens/GettingStarted/__tests__/GettingStarted.spec.tsx, src/pages/guide/screens/Guide/Guide.scss, src/pages/guide/screens/Guide/Guide.tsx, src/pages/guide/screens/Guide/__tests__/Guide.spec.tsx, src/pages/guide/screens/Videos/Videos.tsx, src/pages/my-profile/screens/MyProfile/MyProfileMobile.tsx, src/pages/my-profile/screens/MyProfile/__tests__/MyProfileMobile.spec.tsx, src/utils/index.ts, src/utils/setup-mocks.ts, src/utils/tabs.ts
- Fixed tooltip sizing in smaller phone screens
- Fixed back button not navigating back to proper pages
- Fixed Ui issues
- Open new tab when clicking on blog
- Added embla carousel library for the Carousel component
https://github.com/user-attachments/assets/1a506ec0-33cf-4b2e-95d3-ed6baa7bf0e0
https://github.com/user-attachments/assets/b6e539cd-8658-4238-8370-eb8d1d0efc66
https://github.com/user-attachments/assets/4029b759-89e8-49ad-b476-b9d4c9d0c935
https://github.com/user-attachments/assets/b1093d14-ca38-4d4b-a119-dfacb3ac8686
=> Ameerul /Fix p2p guide bugs

src/components/BuySellForm/BuySellAmount/BuySellAmount.scss, src/components/BuySellForm/BuySellAmount/BuySellAmount.tsx, src/components/BuySellForm/BuySellForm.tsx, src/components/BuySellForm/BuySellPaymentSection/BuySellPaymentSection.tsx, src/components/BuySellForm/BuySellPaymentSection/__tests__/BuySellPaymentSection.spec.tsx, src/components/BuySellForm/__tests__/BuySellForm.spec.tsx, src/components/PaymentMethodCard/PaymentMethodCard.tsx, src/components/PaymentMethodForm/PaymentMethodForm.tsx
- Added logic to check if user's balance is low to show low balance error message in buy sell form
https://github.com/user-attachments/assets/ec6cbd15-f44a-470f-bd2b-dbc0684a74b9
=> Ameerul / FEQ-2595 Sell order missing banner when advertiser has no balance

package-lock.json, package.json
- updated api-hooks package which fixes the firefox login issue
=> Ameerul / FEQ-2585 [Firefox] Not able to login from endpoint page

package-lock.json, package.json
=> Revert "Ameerul / FEQ-2585 [Firefox] Not able to login from endpoint page"

.github/workflows/smoketests.yml
We need to make an API call to the regent markets repo to kick off the tests.
=> Run P2P-V2 tests at commit stage.

src/utils/business-hours.ts
Fixed the first character of the translated days.
=> farrah/WEBREL-3198/fix: day translation

src/components/BlockedScenarios/BlockedScenarios.tsx, src/pages/buy-sell/screens/BuySellTable/BuySellTableRenderer/BuySellTableRenderer.tsx, src/pages/my-ads/screens/MyAdsEmpty/MyAdsEmpty.tsx
- Fixed the text alignment on safari browser for ActionScreen titles as it was positioned to the left and not centered.
- Fixed the issue for BlockedScenarios, BuySellTableRenderer, MyAdsEmpty component
=> Ameerul / FEQ-2677 For safari browser Text alignment for  the empty ads state on buy/sell  and My ads page is Left aligned

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/routes/AppContent/index.tsx
=> [FEQ-2603] Nada/fix: scenario for restricted countries

src/App.tsx, src/components/ErrorBoundary/ErrorBoundary.tsx, src/components/Modals/FallbackErrorModal/FallbackErrorModal.scss, src/components/Modals/FallbackErrorModal/FallbackErrorModal.tsx, src/components/Modals/FallbackErrorModal/__tests__/FallbackErrorModal.spec.tsx, src/components/Modals/FallbackErrorModal/index.ts, src/components/Modals/index.ts
- Changed UI for ErrorBoundary component, now it shows FallbackErrorModal
- Added new Modal
- Added test cases for FallbackErrorModal
https://github.com/user-attachments/assets/9a52c780-6ec4-45fa-b792-754fe09e9ff3
=> Ameerul / FEQ-2615 Create error page when user needs to refresh the page

package-lock.json, package.json, src/pages/guide/screens/FAQs/FAQs.scss, src/pages/guide/screens/FAQs/FAQs.tsx, src/pages/guide/screens/Guide/Guide.tsx, src/pages/guide/screens/Guide/__tests__/Guide.spec.tsx
- Updated deriv-com/ui library to 1.35.6 where I had implemented the changes for Accordion
- Added refs and function to enable scrolling to the Accordion when it is opened.
- Removed scrolling ability in Accordion Content since it is not needed and when the user hovered over the content, it would add a scrollbar which made it look too clunky
https://github.com/user-attachments/assets/18678b8d-602a-4dfd-b1a5-5140c3ddc48f
=> Ameerul / FEQ-2628 [[FE] - P2P Guide - Responsive] - [UI Bugs] AutoScroll Issue + Text readjustment in FAQ cards

src/components/AppFooter/AppFooter.tsx
- Checked if the user is in production environment, if so, hide the Endpoint link in the footer
=> Ameerul / P2PS-4290 Hide endpoint link when connected to the default server

package-lock.json, package.json
Update the analytics version to the latest.
=> farrah/P2PS-4289/fix: update analytics version

package-lock.json, package.json
Updated analytics package version.
=> farrah/P2PS-4333/fix: update analytics version

src/hooks/custom-hooks/useSendbird.ts
- Removed custom filter for the messages to fetch all messages
=> Ameerul / P2PS-4352 Chat message disappears from counterparty who is mobile user

global.d.ts, src/hooks/custom-hooks/useDatadog.ts
Fixed initialisation of DD RUM.
=> farrah/fix: dd rum initialisation

src/hooks/custom-hooks/usePoiPoaStatus.ts
Added a new check for idv-authenticated users. This will allow the users to access P2P if they uploaded POI with photo.
=> farrah/P2PS-4314/fix: added a new check for idv-authenticated users

src/components/AppHeader/Notifications/Notifications.tsx, src/components/Modals/DailyLimitModal/DailyLimitModal.tsx, src/components/Modals/DailyLimitModal/__tests__/DailyLimitModal.spec.tsx, src/hooks/api/notification/__tests__/useNotificationList.spec.ts, src/hooks/api/notification/useNotificationList.ts, src/hooks/api/notification/useNotificationUpdate.ts
=> Revert "farrah/integrate buildship"

src/components/Modals/AvailableP2PBalanceModal/AvailableP2PBalanceModal.scss, src/components/Modals/AvailableP2PBalanceModal/AvailableP2PBalanceModal.tsx
Modified the message we show regarding the available balance.
=> farrah/P2PS-3351/fix: available balance message

.github/workflows/build-and-deploy-test.yml
=> farrah/ fix: remove pr folder

src/components/AdvertiserName/FollowUserButton/FollowUserButton.tsx
Fixed the issues on follow buttons when translated.
=> farrah/P2PS-4381/fix: translation issues

index.html
Reverts deriv-com/p2p#416
we've already checked what was needed and this change is no longer needed.
=> Revert "Shayan/setup zaraz"

public/localstorage-sync.html, src/hooks/custom-hooks/useOAuth.ts
- When user redirects from tradershub outsystems to p2p via clicking on p2p in tradershub, we will grab the authtoken from Cookies which is handled from tradershub side, and we grab it, store it in authToken and login using the given authToken
=> Ameerul / P2PS-4645 Sync login for tradershub Outsystems with p2p.deriv.com

package-lock.json, package.json, src/hooks/api/notification/useNotificationList.ts, src/hooks/api/notification/useNotificationUpdate.ts, src/main.tsx
- Updated api-hooks package to 1.7.1
- removed all the TS expect errors related to notifications
- passed accountType and currency props to the AppDataProvider to grab USD CR account when logging in
https://github.com/user-attachments/assets/b6146a5f-a42b-4b51-baf5-49eeac9fddf8
=> Ameerul / PLA-1882 Account Switching Across Tabs

src/components/Modals/SafetyAlertModal/SafetyAlertModal.scss, src/components/Modals/SafetyAlertModal/SafetyAlertModal.tsx, src/components/Modals/SafetyAlertModal/__tests__/SafetyAlertModal.spec.tsx, src/components/Modals/SafetyAlertModal/index.ts, src/components/Modals/index.ts, src/routes/AppContent/index.tsx
- Added new safety alert modal to help prevent scams
https://github.com/user-attachments/assets/47747832-ad29-49c4-afc5-42f0562cd622
=> Ameerul / P2PS-4790 Safety Alert Banner for P2P Scam

src/components/Modals/SafetyAlertModal/SafetyAlertModal.tsx
- Wrapped Safety Alert Modal Header with localize
=> Ameerul / WEBREL-3618 Safety alert is not translating in all languages

src/components/AppHeader/CurrencyIcon/CurrencyIcon.tsx
- Added temp fix to replace the tusdt and eusdt icon with UsdT string
https://github.com/user-attachments/assets/29d409dc-0f10-456f-afc1-062da11f2bb1
=> Ameerul / WEBREL-3630 The minified error still showing when login with only crypto account

package-lock.json, package.json, public/front-channel.html, src/App.tsx, src/components/AppHeader/AppHeader.tsx, src/components/AppHeader/__tests__/AppHeader.spec.tsx, src/hooks/custom-hooks/useOAuth.ts, src/routes/AppContent/index.tsx, src/routes/CallbackPage.tsx, src/routes/routes-config.ts, src/utils/browser.ts
=> Revert "Revert "Ameerul / FEWP-366 Migrate P2P standalone to OIDC""

src/routes/CallbackPage.tsx
- Added logic to group all the tokens, currencies, accts, so we can check which one is tied to the USD currency. If USD auth token is there, return that auth token, else we return the first token.
=> Ameerul / ENGT-1776 If a client has first currency as Crypto, He will be blocked to use P2P

src/routes/CallbackPage.tsx
=> Ameerul / WEBREL-3817 When user has only Crypto account and tries to login to standalone P2P application , the error message displayed is incorrect

.github/workflows/build-and-deploy-test.yml
=> Revert "fix: modify workflow"

src/components/AppHeader/AppHeader.tsx, src/components/AppHeader/__tests__/AppHeader.spec.tsx, src/routes/AppContent/index.tsx, src/stores/index.ts, src/stores/useIsLoadingOidcStore.ts
- Check if arrayList is not empty
=> Ameerul / TRAH-5932 Showing callback function multiple times before showing P2P

src/routes/AppContent/index.tsx
Fixed the condition to show the loader.
=> farrah/ fix: loader

src/routes/AppContent/index.tsx
- Moved setter down for the oidc tokens comparison check
=> Ameerul / TRAH-5945 Showing Glimpse of Demo Account when User is already on Real Account

src/hooks/custom-hooks/useOAuth.ts, src/routes/AppContent/index.tsx
- added show error modal if invalid token
- replaced redirectToAuth with reloading page
=> Ameerul / TRAH-5948 Infinite loading firefox 

src/components/Dropdown/Dropdown.tsx, src/constants/ad-constants.ts, src/pages/buy-sell/components/SortDropdown/SortDropdown.tsx, src/pages/buy-sell/screens/BuySellHeader/BuySellHeader.tsx, src/pages/buy-sell/screens/BuySellTable/BuySellTable.tsx
- Replaced dropdown from ui library to the local one since I can make changes directly there to fix the dropdown value not updating dynamically.
- Show exchange rate (high-low) or (low-high) depending on if user selected Buy or Sell tabs.
https://github.com/user-attachments/assets/4e499818-4dac-4cbb-97cb-2bd6d31587a1
=> Ameerul / P2PS-5218 Improve "Sort By" Options – Clearly Define Sorting Criteria

src/pages/guide/screens/Blog/Blog.tsx
Make the blog title clickable.
=> farrah/P2PS-5213/fix: blog title

src/hooks/custom-hooks/useOAuth.ts
- added check for invalid token in oAuth
=> Ameerul / TRAH-6045 P2P hangs with service token error

src/pages/orders/screens/OrderDetails/OrderDetails.tsx, src/pages/orders/screens/Orders/OrdersTableRow/OrdersTableRow.tsx, src/utils/__tests__/order-utils.spec.ts, src/utils/order-utils.ts
- Removed isOrderSeen which handles making the row red if the order was not seen previously.
=> Ameerul / P2PS-5225 Fix Color & Spacing Issues in Past Orders Table

src/components/AppHeader/AppHeader.tsx, src/components/AwarenessBanner/AwarenessBanner.tsx, src/components/AwarenessBanner/__tests__/AwarenessBanner.spec.tsx, src/components/BuySellForm/BuySellForm.scss, src/components/BuySellForm/BuySellFormDisplayWrapper.tsx, src/components/BuySellForm/__tests__/BuySellForm.spec.tsx, src/components/Modals/FilterModal/FilterModal.scss, src/components/Modals/FilterModal/FilterModal.tsx, src/components/Modals/FilterModal/__tests__/FilterModal.spec.tsx, src/pages/buy-sell/components/CurrencyDropdown/CurrencyDropdown.scss, src/pages/buy-sell/components/CurrencyDropdown/CurrencyDropdown.tsx, src/pages/buy-sell/components/CurrencyDropdown/__tests__/CurrencyDropdown.spec.tsx, src/pages/buy-sell/screens/BuySell/__tests__/BuySell.spec.tsx, src/pages/buy-sell/screens/BuySellTable/BuySellTable.scss, src/pages/buy-sell/screens/BuySellTable/BuySellTable.tsx, src/pages/buy-sell/screens/BuySellTable/__tests__/BuySellTable.spec.tsx, src/pages/my-ads/screens/MyAds/MyAds.tsx, src/pages/my-ads/screens/MyAds/MyAdsTable/MyAdsDisplayWrapper.scss, src/pages/my-ads/screens/MyAds/MyAdsTable/MyAdsTable.scss, src/pages/my-profile/screens/MyProfile/MyProfile.tsx, src/pages/my-profile/screens/MyProfile/MyProfileMobile.tsx, src/pages/orders/screens/Orders/OrdersTable/OrdersTable.scss, src/pages/orders/screens/Orders/OrdersTable/OrdersTable.tsx
- Stored new local storage value to check if the user has closed the awareness banner.
- Will clear it once the user clicks logout
- Removed AwarenessBanner from MyAds and MyProfile page
- Fixed the styles (mainly heights) when the banner is shown and when it is hidden.
https://github.com/user-attachments/assets/381a611d-ffd8-46d7-ba69-479305bcf37a
https://github.com/user-attachments/assets/2e4c40c3-4542-4b83-b4e5-7a1bcec4586c
=> Ameerul / P2PS-5226 Fix Persistent Warning Message

src/components/AdvertsTableRow/AdvertsTableRow.tsx
- Reduced the max width size of the payment methods container in buy/sell page
=> Ameerul / P2PS-5266 Buy/Sell Buttons' Texts are Broken

src/pages/orders/screens/Orders/OrdersTable/OrdersTable.scss, src/pages/orders/screens/Orders/OrdersTable/OrdersTable.tsx
- Added `Rating` Header text to the column
- adjusted last child margin to match with rating button
=> Ameerul / P2PS-5264 Past Orders Tab - Header Item 'Rating' Missing

src/App.tsx, src/components/AppHeader/AppHeader.tsx, src/hooks/custom-hooks/useOAuth.ts, src/routes/AppContent/index.tsx
- Removed check for hydra_fe since its already released to prod
- Instead check if the user is in staging or production to use OIDC
=> Ameerul / TRAH-6012 [OIDC] P2P Require multiple log outs to fully log out of P2P - Safari

src/components/Modals/BusinessHoursModal/BusinessHoursModalMain/BusinessHoursModalMain.tsx, src/components/Modals/BusinessHoursModal/__tests__/BusinessHoursModal.spec.tsx
Removed the disclaimer on business hours modal.
=> fix: removed disclaimer

src/components/DatePicker/DatePicker.scss, src/components/DatePicker/DatePicker.tsx, src/components/DateTextField/DateTextField.scss, src/pages/orders/components/OrdersDateSelectionFullPage/OrdersDateSelectionFullPage.tsx
- Highlighted todays date in the calendar
- Changed the label text for the date text field since it was getting cut off
=> Ameerul / P2PS-5279 Past Orders Calendar Improvement (Today's Date Highlight + Dates Not Being Cut-off)

src/components/Modals/BusinessHoursModal/BusinessHoursModalMain/BusinessHoursModalMain.tsx
- Added `Business hours are displayed in your local time` info in Business Hours Modal
=> Ameerul / P2PS-5280 Clearly Indicate Timezone Information (P2P Platform)

src/pages/my-profile/screens/PaymentMethods/PaymentMethodsEmpty/PaymentMethodsEmpty.tsx, src/pages/my-profile/screens/PaymentMethods/PaymentMethodsEmpty/__tests__/PaymentMethodsEmpty.spec.tsx, src/pages/my-profile/screens/PaymentMethods/PaymentMethodsList/AddNewButton.tsx, src/pages/my-profile/screens/PaymentMethods/PaymentMethodsList/__test__/AddNewButton.spec.tsx, src/pages/my-profile/screens/PaymentMethods/PaymentMethodsList/__test__/PaymentMethodsListContent.spec.tsx, src/reducers/__tests__/advertiserPaymentMethodsReducer.spec.ts, src/reducers/advertiserPaymentMethodsReducer.tsx
Fixed CTAs on payment methods section.
=> farrah/fix: ctas

src/pages/guide/screens/FAQs/FAQs.tsx
- Updated content for How to register for Deriv P2P FAQ:
=> Ameerul / P2PS-5216 [P2P] Update FAQ Section – Include PNV & Nickname Requirement for P2P Registration

src/components/Modals/AvailableP2PBalanceModal/AvailableP2PBalanceModal.tsx
Updated the information on available balance.
=> farrah/fix: update available balance

package-lock.json, package.json
- Updated auth-client package to 1.4.6 to remove the `Logging into your account` text when callback page is shown to align with the other apps using OIDC
=> Ameerul / TRAH-6244 [OIDC] Remove logging into your account text (P2P)

src/routes/CallbackPage.tsx
Fixed the redirection to callback page.
=> fix: callback page

src/routes/CallbackPage.tsx
=> Revert "fix: callback page"

src/routes/CallbackPage.tsx
=> fix: replace history state

src/routes/CallbackPage.tsx
=> Revert "fix: replace history state"

src/routes/CallbackPage.tsx
=> fix: replace state

src/routes/AppContent/index.tsx
=> fix: unhandled rejection

src/routes/AppContent/index.tsx, src/routes/CallbackPage.tsx
=> fix: history state

src/routes/CallbackPage.tsx
=> fix: revert callback change

src/components/AppFooter/AccountLimits.tsx, src/components/AppFooter/__tests__/AccountLimits.spec.tsx, src/components/AppFooter/__tests__/AppFooter.spec.tsx, src/components/AppHeader/AppHeader.tsx, src/components/AppHeader/MobileMenu/MobileMenuConfig.tsx, src/components/PNVBanner/PNVBanner.tsx, src/components/PNVBanner/__tests__/PNVBanner.spec.tsx, src/components/Verification/Verification.tsx, src/components/Verification/__tests__/Verification.spec.tsx, src/constants/url.ts, src/hooks/custom-hooks/useShouldRedirectToLowCodeHub.ts, src/pages/guide/screens/FAQs/FAQs.tsx, src/pages/guide/screens/Guide/__tests__/Guide.spec.tsx
Redirection to Accounts OS based on the feature flag.
=> farrah/fix: redirection to accounts os

src/main.tsx
Fixed the account being authorized.
=> farrah/fix: account syncing

src/main.tsx
Updated the url param used for authorizing.
=> farrah/fix: update param

src/main.tsx
Fixed setting of account currency.
=> farrah/fix: setting of currency

src/main.tsx, src/routes/CallbackPage.tsx
=> fix: account sync

src/App.tsx, src/hooks/custom-hooks/useTMB.ts, src/main.tsx
- The current PR focuses on creating a custom component which renders the application if there is a session
- Waits for the response from useTMB and sets the session after a successful response
=> Update app initialization logic for TMB sessions/active endpoint

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx
Changed the content of blocked crypto users.
=> farrah/fix: content

src/App.tsx
Show the Logout button on Endpoint page.
=> farrah/fix: show header on endpoint page

src/routes/CallbackPage.tsx
Handle the browser's back button by preventing the access to callback page.
=> farrah/fix: back button

src/routes/AppContent/index.tsx
=> Revert "Ameerul / ENGT-2414 On Responsive mode seeing Infinite loading on tapping Back button from P2P page"

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/routes/AppContent/index.tsx
Fixed the scenario when a user with a crypto account accesses P2P then creates a real USD account.
=> farrah/ fix: blocked scenarios

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/routes/AppContent/index.tsx
=> Revert "farrah/ fix: blocked scenarios"

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/routes/AppContent/index.tsx
=> farrah/fix: blocked scenarios

src/components/BlockedScenarios/BlockedScenarios.tsx, src/components/BlockedScenarios/__tests__/BlockedScenarios.spec.tsx, src/hooks/api/account/index.ts, src/hooks/api/account/useCreateRealAccount.ts, src/hooks/api/account/useCreateWalletAccount.ts
Implemented adding of an account wallet.
=> farrah/fix: add wallet account

src/pages/guide/screens/FAQs/FAQs.tsx
Updated the content on FAQ page.
=> fix: update content

src/hooks/custom-hooks/useTMBFeatureFlag.ts
Updated the hook to get the feature flag.
=> farrah/fix: refactor-tmb

src/hooks/custom-hooks/useTMBFeatureFlag.ts
=> farrah/fix: tmb refactor

src/constants/url.ts
=> farrah/fix: updated video

src/App.tsx, src/components/AppHeader/__tests__/AppHeader.spec.tsx, src/hooks/custom-hooks/useGetHubEnabledCountryList.ts, src/hooks/custom-hooks/useShouldRedirectToLowCodeHub.ts, src/stores/index.ts, src/stores/useHubEnabledCountryListStore.ts
Refactor the hook for checking the hub-enabled country list in Firebase.
=> farrah/refactor: hub-enabled-country-list flag

package-lock.json, package.json, src/hooks/custom-hooks/useShouldRedirectToLowCodeHub.ts
Fixed the redirections to .be and .me.
=> farrah/ENGT-3049/fix: be and me redirections

src/public/.well-known/apple-app-site-association
Fixed the redirection from web to mobile.
=> fix: deeplinking

public/.well-known/apple-app-site-association
Reverted the deeplink changes.
=> farrah/fix: revert deeplink

src/components/BlockedScenarios/BlockedScenarios.tsx, src/constants/api-error-codes.ts, src/routes/AppContent/index.tsx
Updated the content for users who have changed their email address and trying to access P2P within a 24-hr cooldown period.
=> farrah/P2PS-5365/fix: updated the blocked content

src/hooks/custom-hooks/useOAuth.ts
Fixed the logout issue by using WS instead of oAuth logout.
=> farrah/fix: logout issue

src/constants/url.ts
Updated the oauth url to handle .me and .be.
=> farrah/fix: oauth url

src/components/AppFooter/Deriv.tsx, src/components/AppHeader/AppLogo/AppLogo.tsx, src/components/AppHeader/HeaderConfig.tsx, src/components/AppHeader/MobileMenu/MobileMenuConfig.tsx, src/constants/url.ts, src/hooks/custom-hooks/useShouldRedirectToLowCodeHub.ts, src/pages/guide/screens/FAQs/FAQs.tsx, src/pages/orders/components/ChatMessages/ChatMessages.tsx
=> farrah/WEBREL-5070/fix: redirections

src/App.tsx, src/components/AppHeader/AppHeader.tsx, src/components/AppHeader/__tests__/AppHeader.spec.tsx, src/hooks/api/advertiser/p2p-advertiser/__tests__/useAdvertiserInfo.spec.ts, src/hooks/api/advertiser/p2p-advertiser/useAdvertiserInfo.ts, src/routes/AppContent/index.tsx
=> farrah/fix: ui for migrated users
